[project]
authors = ["Hannah Zafar <hannah.zafar@nasa.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "VIIRS-download"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
earthaccess = ">=0.15.1,<0.16"
xarray = ">=2025.12.0,<2026"
h5netcdf = ">=1.8.0,<2"
dask = ">=2026.1.1,<2027"
ipykernel = ">=7.1.0,<8"
